CREATE TABLE dbo.SKU (
    ID INT IDENTITY PRIMARY KEY,
    Code AS 's' + CAST(ID AS VARCHAR(10)),
    Name VARCHAR(50) NOT NULL,

    CONSTRAINT UQ_SKU_Code UNIQUE(Code)
);

CREATE TABLE dbo.Family (
    ID INT IDENTITY PRIMARY KEY,
    SurName VARCHAR(50) NOT NULL,
    BudgetValue DECIMAL(10, 2) NOT NULL
);

CREATE TABLE dbo.Basket (
    ID INT IDENTITY PRIMARY KEY,
    ID_SKU INT NOT NULL,
    ID_Family INT NOT NULL,
    Quantity INT NOT NULL CONSTRAINT CHK_Quantity CHECK (Quantity >= 0),
    Value DECIMAL(10, 2) NOT NULL CONSTRAINT CHK_Value CHECK (Value >= 0),
    PurchaseDate DATE NOT NULL DEFAULT GETDATE(),
    DiscountValue DECIMAL(10, 2) NULL,

    CONSTRAINT FK_Basket_SKU FOREIGN KEY (ID_SKU) REFERENCES dbo.SKU(ID),
    CONSTRAINT FK_Basket_Family FOREIGN KEY (ID_Family) REFERENCES dbo.Family(ID)
);